import React from 'react';
import {
  Document,
  Page,
  Text,
  StyleSheet,
  Font,
  View,
  PDFDownloadLink
} from '@react-pdf/renderer';

import kannadaFont from '../fonts/NotoSansKannada-Regular.ttf'
import hindiFont from '../fonts/NotoSansDevanagari-VariableFont_wdth,wght.ttf'


// ✅ Register Fonts
Font.register({
  family: 'KannadaFont',
  src: kannadaFont,
});
Font.register({
  family: 'HindiFont',
  src: hindiFont,
});
Font.register({
  family: 'TamilFont',
  src: '/src/fonts/NotoSansTamil-Regular.ttf',
});

// ✅ Styles
const styles = StyleSheet.create({
  // page: {
  //   padding: 30,
  //   fontSize: 16,
  // },
  // section: {
  //   marginBottom: 20,
  // },
 page: {
   paddingTop: 40,
   paddingBottom: 60,
   paddingHorizontal: 40,
   fontSize: 12,
   lineHeight: 1.6,
   position: 'relative',
 },
 section: {
   marginBottom: 15,
 },
 footer: {
   position: 'absolute',
   bottom: 30,
   left: 40,
   right: 40,
   textAlign: 'center',
   fontSize: 10,
   color: 'grey',
 },
  kannada: {
    fontFamily: 'KannadaFont',
  },
  hindi: {
    fontFamily: 'HindiFont',
  },
  tamil: {
    fontFamily: 'TamilFont',
  },
});
const getFontStyle = (language : string) => {
  // console.log(language)
    switch (language) {
      case 'kn':
        return styles.kannada;
      case 'hi':
        return styles.hindi;
      case 'ta':
        return styles.tamil;
      default:
        return {};
    }
  };
// ✅ PDF Component
const MyMultilingualPDF = ({content , language}:{content : string , language : string}) => (
  
  
   <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.section}>
          <Text style={getFontStyle(language)}>{content}</Text>
        </View>
        <Text style={styles.footer}>Generated by Sahayak ai</Text>
      </Page>
    </Document>
);

export default MyMultilingualPDF;


