import jsPDF from 'jspdf';

export const generatePDF = (content: string, filename: string = 'document') => {
  const doc = new jsPDF();
  
  // Set font
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  
  // Add title
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Sahayak AI - Generated Content', 20, 20);
  
  // Add content
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  
  // Split content into lines that fit the page width
  const lines = doc.splitTextToSize(content, 170);
  
  let yPosition = 40;
  const pageHeight = doc.internal.pageSize.height;
  
  lines.forEach((line: string) => {
    if (yPosition > pageHeight - 20) {
      doc.addPage();
      yPosition = 20;
    }
    doc.text(line, 20, yPosition);
    yPosition += 7;
  });
  
  // Add footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.text(`Page ${i} of ${pageCount}`, 20, pageHeight - 10);
    doc.text('Generated by Sahayak AI Teaching Assistant', 120, pageHeight - 10);
  }
  
  // Save the PDF
  doc.save(`${filename}.pdf`);
};